nav:
  - text: 首页
    url: index.html
  - text: 分类目录 
    url: navigations/categories.html
  - text: 文章归档
    url: navigations/archives.html
  - text: 联系我
    url: navigations/contact.html
  - text: 友情链接
    url: navigations/links.html
    
author:
    name: ruilibuaa
    email: xkzbeta@outlook.comment
    imageLink: https://avatars.githubusercontent.com/minixalpha
    simpleIntro: 我是 minixalpha
    
username: ruilibuaa
baseurl: /StrayBirds
markdown: redcarpet
safe: false
highlighter: true
title: 飞鸟集
description: 人生到处知何似，应似飞鸿踏雪泥
theme: kunka
disqusname: minixalpha
