######################### theme kunka condigure ##############################################
# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate: 8


username: ruilibuaa
baseurl: /StrayBirds
markdown: redcarpet
safe: false
highlighter: true
title: 飞鸟集
description: 人生到处知何似，应似飞鸿踏雪泥
theme: kunka
disqusname: minixalpha
